kind: Deployment
apiVersion: apps/v1
metadata:
  name: simple-static-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-static-site-app
  template:
    metadata:
      labels:
        app: simple-static-site-app
    spec:
      containers:
      - name: simple-static-site
        image: simple-static-site:1.0.0
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: simple-static-site-service
spec:
  ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-static-site-app